### ISSUE TITLE
Inverter read battery total capacity (norminal) wrong (50Ah) while serial log show different value (210Ah)

### ISSUE THREAD

**Issue by paulsteigel** [ArminJo/JK-BMSToPylontechCAN#13]
Hi Armin,
Today I tried a test with Arduino Uno R3 (ATMega328) at my parent's home and have the inverter connected successfully with the JK-BMS. However, Battery Capacity shown by Inverter was only 50Ah while the real value (read by Serial log was 210Ah - this is the correct number). Other values were correct such as: SOC, voltage...etc, only the total capacity of the battery was wrong!
I doubt the CAN converter module (code) have a bit of problem on calculating. Can you please be so kind to help checking this with thanks.
Yours very faithfully,
Dang Dinh Ngoc
===============QUOTE SERIAL LOG========================
C:\Users\Admin\Desktop\JK-BMSToPylontechCAN-main\JK-BMSToPylontechCAN-main\JK-BMSToPylontechCAN\JK-BMSToPylontechCAN.ino
Version 2.2.2 from Oct 19 2023
No I2C LCD connected at address 0x27
Serial to JK-BMS started with 115200 bit/s!
CAN started with 500 kbit/s!
Page switching button is at pin 2
At long press, CAN Info page is entered and additional debug data is printed as long as button is pressed
2000 ms between 2 BMS requests
2000 ms between 2 CAN transmissions
LCD Backlight timeout is 5 min

* BMS INFO *
Protocol Version Number=1
Software Version Number=11.XW_S11.272__
Modify Parameter Password=123456a@
# External Temperature Sensors=2

* BATTERY INFO *
Manufacturer Date=2310
Manufacturer Id=Input Userda210Ah0804202
Device ID String=Input Us
Device Address=1
Total Battery Capacity[Ah]=210, Low Capacity Alarm Percent=20
Charging Cycles=8
Total Charging Cycle Capacity=1710
# Battery Cells=16, Cell Count=16

* VOLTAGE PROTECTION INFO *
Battery Overvoltage Protection[mV]=56000, Undervoltage=48000
Cell Overvoltage Protection[mV]=3500, Recovery=3450, Delay[s]=5
Cell Undervoltage Protection[mV]=3000, Recovery=3050, Delay[s]=5
Cell Voltage Difference Protection[mV]=300
Discharging Overcurrent Protection[A]=80, Delay[s]=300
Charging Overcurrent Protection[A]=60, Delay[s]=30

* TEMPERATURE PROTECTION INFO *
Power MosFet Temperature Protection=100, Recovery=80
Sensor1 Temperature Protection=100, Recovery=100
Sensor1 to Sensor2 Temperature Difference Protection=20
Charge Overtemperature Protection=70, Discharge=70
Charge Undertemperature Protection=-20, Recovery=-10
Discharge Undertemperature Protection=-20, Recovery=-10

* MISC INFO *
Balance Starting Cell Voltage=[mV]2900
Balance Triggering Voltage Difference[mV]=10

Current Calibration[mA]=834
Sleep Wait Time[s]=10

Dedicated Charge Switch Active=0
Start Current Calibration State=0
Battery Actual Capacity[Ah]=210

Total Runtime Minutes=18848 ->   13D02H08M
* CELL INFO *
16 Cells, Minimum=3273 mV, Maximum=3281mV, Delta=8 mV, Average=3279 mV
 1=3280 mV,  2=3279 mV,  3=3279 mV,  4=3278 mV,  5=3279 mV,  6=3278 mV,  7=3280 mV,  8=3281 mV, 
 9=3273 mV,  10=3279 mV, 11=3278 mV, 12=3279 mV, 13=3280 mV, 14=3280 mV, 15=3280 mV, 16=3281 mV, 

Warning: CellOvervoltageProtectionMillivolt value 3500 mV > 3450 mV is not recommended for LiFePO4 chemistry. There is less than 1% extra capacity above 3.5V.
Temperature: Power MosFet=31, Sensor 1=27, Sensor 2=27
SOC[%]=38 -> Remaining Capacity[Ah]=79
Battery Voltage[V]=52.46, Current[A]=-9.34, Power[W]=-489, Difference to full[V]=3.5
===============END QUOTE===============================

**Comment by ArminJo** [comment]
> At long press, CAN Info page is entered and additional debug data is printed as long as button is pressed

What is the output of the debug page???

**Comment by paulsteigel** [comment]
Hi Armin,
Thank you for your quick response. I connected a button to pin 3 (on A) and C to Ground (my button has 4 pin) - I currently dont have a 1K resitor to limit current - sorry. The following data is printed, I dont see CAN debuging data printed. I might be wrong then!

1= 0 % |    0,  2= 0 % |    0,  3= 0 % |    0,  4= 0 % |    0,  5= 0 % |    0,  6= 0 % |    0,  7= 0 % |    0,  8= 0 % |    0, 
 9=72 % |  150, 10= 0 % |    0, 11=27 % |   57, 12= 0 % |    0, 13= 0 % |    0, 14= 0 % |    0, 15= 0 % |    0, 16= 0 % |    0, 
Cell Maximum percentages
 1= 2 % |    7,  2= 0 % |    0,  3= 0 % |    0,  4= 0 % |    0,  5= 0 % |    0,  6= 0 % |    0,  7= 1 % |    6,  8=18 % |   59, 
 9= 0 % |    0, 10= 0 % |    0, 11= 0 % |    0, 12= 0 % |    0, 13= 2 % |    7, 14=15 % |   49, 15=16 % |   52, 16=43 % |  138, 

Warning: CellOvervoltageProtectionMillivolt value 3500 mV > 3450 mV is not recommended for LiFePO4 chemistry. There is less than 1% extra capacity above 3.5V.
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, not active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, active

Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, not active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, not active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, not active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, not active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, active
Battery Voltage[V]=52.44, Current[A]=-9.47, Power[W]=-496, Difference to full[V]=3.6
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, not active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, active
Battery Voltage[V]=52.43, Current[A]=-9.60, Power[W]=-503, Difference to full[V]=3.6
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, not active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, active
Battery Voltage[V]=52.43, Current[A]=-9.87, Power[W]=-517, Difference to full[V]=3.6
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, not active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, not active
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, active
Battery Voltage[V]=52.43, Current[A]=-10.00, Power[W]=-524, Difference to full[V]=3.6
Battery Voltage[V]=52.43, Current[A]=-9.60, Power[W]=-503, Difference to full[V]=3.6
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, not active
Battery Voltage[V]=52.43, Current[A]=-9.20, Power[W]=-482, Difference to full[V]=3.6
Charging MosFet enabled, active | Discharging MosFet enabled, active | Balancing enabled, active
Battery Voltage[V]=52.43, Current[A]=-9.47, Power[W]=-496, Difference to full[V]=3.6
Battery Voltage[V]=52.43, Current[A]=-9.74, Power[W]=-510, Difference to full[V]=3.6
Total Runtime Minutes=18920 ->   13D03H20M
* CELL INFO *
16 Cells, Minimum=3270 mV, Maximum=3280mV, Delta=10 mV, Average=3276 mV
 1=3279 mV,  2=3278 mV,  3=3278 mV,  4=3276 mV,  5=3278 mV,  6=3276 mV,  7=3279 mV,  8=3279 mV, 
 9=3271 mV,  10=3275 mV, 11=3270 mV, 12=3276 mV, 13=3278 mV, 14=3279 mV, 15=3279 mV, 16=3280 mV, 

* CELL STATISTICS *
Total balancing time=314 s ->   0D00H05M14S
Cell Minimum percentages

SOC[%]=32 -> Remaining Capacity[Ah]=67

**Comment by ArminJo** [comment]
It must look like https://github.com/ArminJo/JK-BMSToPylontechCAN/blob/9f9be264ac7ef9d2e3c29954dffca267e3409461/extras/JK-BMS.log#L70

**Comment by paulsteigel** [comment]
> It must look like
> 
> https://github.com/ArminJo/JK-BMSToPylontechCAN/blob/9f9be264ac7ef9d2e3c29954dffca267e3409461/extras/JK-BMS.log#L70

Hi Armin,
I updated the log file and discovered that CAN data frame does not include Total Capacity in Ah. That is why the Inverter does not reflect / and or calculate and just use its default value! (50Ah).
I also update the CAN log (previous comment) for your reference then!
Ngoc

**Comment by ArminJo** [comment]
I must test it for backward compatibility...

**Comment by paulsteigel** [comment]
Many thanks Armin,
It will be well appreciated by many users like my country then.
Also, I am thinking of adding a mod-bus with MAXRS485 to connect several batteries in parallel (the mater will connect with converter via CAN and slave batteries will connect together using mod-bus.
Thanks again for all your supports!
Ngoc

**Comment by ArminJo** [comment]
Hi Ngoc,
what is the sensible content of the 6 non capacity bytes in frame 0x35F? I guessed some values.

What is the sensible content of `SOCHighDefinition100PPM` as 3. word of frame 0x355, documented in SMA CAN protocol. I did not include it so far.

There should be no difference between the 328 versions, except if this are counterfeit versions.
My two China clone Nanos are working fine.

**Comment by paulsteigel** [comment]
> Hi Ngoc, what is the sensible content of the 6 non capacity bytes in frame 0x35F? I guessed some values.
> 
> What is the sensible content of `SOCHighDefinition100PPM` as 3. word of frame 0x355, documented in SMA CAN protocol. I did not include it so far.
> 
> There should be no difference between the 328 versions, except if this are counterfeit versions. My two China clone Nanos are working fine.

Hi Armin,
Regarding this table, I assume only the 4th and 5th are meaningful for the capacity in Ah to be sent to the inverter. 
![image](https://github.com/ArminJo/JK-BMSToPylontechCAN/assets/8839597/23561484-e339-4bb6-9730-68b755434040)

I am now checking a bit more with other type of batteries to see whether these can be meaningful and worth incorporating into the PylontechCAN. At the moments, the SOC is enough for the inverter to control charging/discharging.

![image](https://github.com/ArminJo/JK-BMSToPylontechCAN/assets/8839597/c72dcc90-ac0a-4041-8057-4750797e8056)
What I am wondering is how the inverter can have this data for some other type of the batteries (SVE5000WM), it can read the Capacity in Ah and also apply a nice charging curve for the battery (see second image). So it means that the Inverter can request more data than we have included in the CAN message and probably have its internal charging computation so far. 
Best,
Ngoc
