### ISSUE TITLE
TJA1050 instead of MCP2515

### ISSUE THREAD

**Issue by anntwel98** [ArminJo/JK-BMSToPylontechCAN#23]
Hi
Can I use TJA1050 Instead of MCP2515!
How about wiring for TJA1050, It only have
Vcc,Rx,Tx and GND.

Thanks,

**Comment by ArminJo** [comment]
1. This is NO issue!
2. You can use TJA1050, because it is on the MCP2515 board too, but then you must simulate the functionality of MCP2515 in software.
